# Generated by Django 4.0.2 on 2022-02-09 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=500)),
                ('year', models.IntegerField(default=1800)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paintings', to='main_app.artist')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
