# Generated by Django 4.0.2 on 2022-02-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_painting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=500)),
                ('body', models.TextField()),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
